services:
    spsostrov.sso:
        class: SPSOstrov\SSO\SSO
        arguments:
          $ssoGatewayUrl: null
          $ssoGatewayCheckUrl: null
          $ssoUserClass: SPSOstrov\SSOBundle\SSOUser

