services:
    _defaults:
        autowire: true
        autoconfigure: true
    SPSOstrov\SSOBundle\:
        resource: '../src/'
        exclude:
            - '../src/SSOBundle.php'
    SPSOstrov\SSOBundle\Controller\:
        resource: '@Bundle/Controller/'
        tags: ['controller.service_arguments']

